// Mock classes generated by Mockito
@GenerateNiceMocks([MockSpec<AuthService>()])
import 'package:edu_flow_frontend/lib/data/services/auth_service.dart';
import 'package:mockito/mockito.dart';

// Mock implementation of AuthService
class MockAuthService extends Mock implements AuthService {}